#!/usr/bin/env python
"""PyTexEditor: A LaTeX GUI editor written in Python.

Usage:
    PyTeXEditor [-v | -h]

Options:
    -h --help       Show this screen.
    -v --verbose    Verbose logging.

"""

from PyTeXEditor.window import Window
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QSize
import sys
import logging
from docopt import docopt


if __name__ == "__main__":
    arguments = docopt(__doc__, version='0.0')
    if arguments["--verbose"] == True:
        logging.basicConfig(encoding='utf-8', level=logging.DEBUG)
    else:
        logging.basicConfig(encoding='utf-8', level=logging.ERROR)
    app = QApplication(sys.argv)
    ex = Window()
    size = QSize()
    size.setHeight(600)
    size.setWidth(800)
    ex.resize(size)
    sys.exit(app.exec())
