name: Tests

on:
  - push
  - pull_request

jobs:
  Linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11']
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        sudo apt install -y texlive
    - name: setup ${{ matrix.os }}
      uses: tlambert03/setup-qt-libs@v1
    - name: Test with tox
      run: tox
  Windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v2
      with:
        packages:
          scheme-basic
    - name: Test with tox
      run: tox